import {
  FiShoppingBag,
  FiCreditCard,
  FiShoppingCart,
  FiShare2,
  FiNavigation,
  FiSmartphone,
  FiTarget,
  FiAward,
  FiCalendar,
  FiPackage,
  FiSun,
  FiInstagram,
  FiHome,
  FiMap,
  FiGift,
  FiDatabase,
  FiUsers,
  FiArchive,
  FiChevronRight,
  FiChevronLeft,
} from "react-icons/fi";

export const iconList = {
  bag: <FiShoppingBag />,
  card: <FiCreditCard />,
  cart: <FiShoppingCart />,
  share: <FiShare2 />,
  nav: <FiNavigation />,
  phone: <FiSmartphone />,
  target: <FiTarget />,
  award: <FiAward />,
  calendar: <FiCalendar />,
  package: <FiPackage />,
  sun: <FiSun />,
  instagram: <FiInstagram />,
  home: <FiHome />,
  map: <FiMap />,
  gift: <FiGift />,
  database: <FiDatabase />,
  users: <FiUsers />,
  archive: <FiArchive />,
  arrowRight: <FiChevronRight />,
  arrowLeft: <FiChevronLeft />,
};
